project_tasks/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from projects.views import ProjectListView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('projects/', include('projects.urls')),
    path('tasks/', include('tasks.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    re_path('^$', ProjectListView.as_view(), name = 'project_list'),
]

tasks/urls.py
from django.urls import path, re_path
from tasks import views

app_name = 'tasks'

urlpatterns = [
    path('', views.ListTask.as_view(), name = 'list'),
    path('create/', views.CreateTask.as_view(), name = 'create'),
    path('delete/<int:pk>/', views.DeleteTask.as_view(), name = 'delete'),
]

templates/includes/messages.html
{% for msg in messages %}
    <div class="alert {{ msg.tags }} alert-dismissible fade show" role="alert">
        <strong>
            {{ msg }}
        </strong>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
{% endfor %}

templates/includes/navbar.html
<nav class="navbar navbar-expand-md navbar-dark bg-dark">
    <a class="navbar-brand" href="{% url 'project_list' %}">Projects Tasks</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
            {% if request.user.is_authenticated %}
                <li class="nav-item active">
                    <span class="nav-link">{{ request.user }}</span>
                </li>
                <li class="nav-item active">
                    <a href="{% url 'tasks:list' %}" class="nav-link">Tasks</a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'logout' %}">Logout</a>
                </li>
            {% else %}
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'login' %}">Login</a>
                </li>
            {% endif %}
            <!-- <li class="nav-item active">
                <a class="nav-link" href="{% url 'project_list' %}">Projects</a>
            </li> -->
        </ul>
    </div>
</nav>