project_tasks/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from projects.views import ProjectListView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('projects/', include('projects.urls')),
    path('tasks/', include('tasks.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    re_path('^$', ProjectListView.as_view(), name = 'project_list'),
]

projects/urls.py
from django.urls import path, re_path
from projects import views

app_name = 'projects'

urlpatterns = [
    path('create-project/', views.ProjectCreate.as_view(), name = 'create'),
    path('delete-project/<int:pk>/', views.ProjectDelete.as_view(), name = 'delete'),
    path('update-project/', views.ProjectUpdate.as_view(), name = 'update'),
    path('project-details/<int:pk>/', views.ProjectDetails.as_view(), name = 'details'),
]

tasks/urls.py
from django.urls import path, re_path
from tasks import views

app_name = 'tasks'

urlpatterns = [
    path('', views.ListTask.as_view(), name = 'list'),
    path('create/', views.CreateTask.as_view(), name = 'create'),
    path('delete/<int:pk>/', views.DeleteTask.as_view(), name = 'delete'),
]

projects/models.py
from django.db import models
from django.conf import settings
from django.contrib.auth.models import Group
from django.urls import reverse_lazy

class Project(models.Model):
    name = models.CharField(max_length = 250)
    start = models.DateField(verbose_name = 'Start Date')
    end = models.DateField(verbose_name = 'End Date')
    # status
    assigned_users = models.ManyToManyField(
        settings.AUTH_USER_MODEL,
        blank = True,
        related_name = 'projects'
    )
    assigned_groups = models.ManyToManyField(
        Group,
        blank = True,
        related_name = 'projects',
    )
    progress = models.PositiveSmallIntegerField(default = 0, editable = False)
    created_by = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete = models.SET_NULL,
        null = True,
        blank = True,
        related_name = 'created_projects',
        editable = False,
    )
    updated_by = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete = models.SET_NULL,
        null = True,
        blank = True,
        related_name = 'updated_projects',
        editable = False,
    )
    updated = models.DateTimeField(auto_now = True)
    created = models.DateTimeField(auto_now_add = True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse_lazy('projects:details', kwargs = {'pk' : self.id})

    class Meta:
        ordering = ('-created', 'name')

projects/forms.py
from django import forms
from django.contrib.auth.models import User, Group
from django.contrib.auth.models import User

from .models import Project


class ProjectForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super(ProjectForm, self).__init__(*args, **kwargs)
        for f in self.fields:
            self.fields[f].widget.attrs['class'] = 'form-control'
            self.fields[f].widget.attrs['placeholder'] = f
        # self.fields['assigned_users'].widget.attrs['class'] += ' select2-multiple'
        # self.fields['assigned_groups'].widget.attrs['class'] += ' select2-multiple'
        self.fields['start'].widget.attrs['class'] += ' date-selector'
        self.fields['end'].widget.attrs['class'] += ' date-selector'
        self.fields['end'].widget.attrs['placeholder'] = 'YYYY-MM-DD'
        self.fields['start'].widget.attrs['placeholder'] = 'YYYY-MM-DD'
        self.fields['start'].widget.attrs['id'] = 'id_task_start'
        self.fields['end'].widget.attrs['id'] = 'id_task_end'

    class Meta:
        model = Project
        fields = ('name', 'start', 'end')


ProjectInlineFormset = forms.inlineformset_factory(
    User,
    Project,
    ProjectForm,
    fk_name = 'created_by',
    # fields = ('name', 'start', 'end', 'assigned_users', 'assigned_groups',),
    can_delete = False,
)

projects/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse_lazy
from django.http import HttpResponseRedirect
from django.views.generic import ListView, CreateView, DeleteView, UpdateView
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.contrib import messages

from .forms import ProjectForm, ProjectInlineFormset
from .models import Project
from tasks.forms import TaskForm


class ProjectDetails(PermissionRequiredMixin, UpdateView):
    model = Project
    template_name = 'projects/details.html'
    context_object_name = 'project'
    permission_required = ('projects.change_projects',)
    form_class = ProjectForm

    def get_context_data(self, *args, **kwargs):
        cxt = super(ProjectDetails, self).get_context_data(*args, **kwargs)
        cxt['task_form'] = TaskForm
        return cxt


class ProjectListView(PermissionRequiredMixin, ListView):
    permission_required = ('projects.view_project',)
    model = Project
    template_name = 'projects/list.html'
    context_object_name = 'projects'

    def get_context_data(self, *args, **kwargs):
        cxt = super(ProjectListView, self).get_context_data(*args, **kwargs)
        cxt['project_form'] = ProjectForm()
        cxt['update_formset'] = ProjectInlineFormset(instance = self.request.user)
        return cxt

    def get_queryset(self):
        return self.request.user.created_projects.all()

    def handle_no_permission(self):
        if self.request.user.is_authenticated:
            return redirect('tasks:list')
        return HttpResponseRedirect(f'{reverse_lazy("login")}?next={self.request.path}')


class ProjectCreate(PermissionRequiredMixin, CreateView):
    permission_required = ('projects.add_project',)
    model = Project
    form_class = ProjectForm
    template_name = 'projects/list.html'

    def form_valid(self, form):
        obj = form.save(commit = False)
        obj.created_by = self.request.user
        obj.updated_by = self.request.user
        obj.save()
        form.save_m2m()
        messages.success(self.request, f'Project {obj.name} created')
        return redirect(reverse_lazy('projects:details', kwargs = {'pk' : obj.id}))

    def form_invalid(self, form):
        cxt = self.get_context_data()
        cxt['project_form'] = cxt['form']
        cxt['projects'] = Project.objects.all()
        messages.error(self.request, 'Please correct form errors and try again')
        return render(self.request, self.template_name, cxt)

    def handle_no_permission(self):
        return HttpResponseRedirect(f'{reverse_lazy("login")}?next={self.request.path}')


class ProjectDelete(PermissionRequiredMixin, DeleteView):
    model = Project
    permission_required = ('projects.delete_project',)
    success_url = reverse_lazy('project_list')

    def get_success_url(self):
        obj = self.get_object()
        messages.info(self.request, f'Project {obj.name} deleted')
        return super(ProjectDelete, self).get_success_url()


class ProjectUpdate(PermissionRequiredMixin, UpdateView):
    permission_required = ('projects.change_project',)
    model = Project
    template_name = 'projects/list.html'
    success_url = reverse_lazy('project_list')

    def post(self, request):
        formset = ProjectInlineFormset(request.POST, instance = request.user)
        if formset.is_valid():
            instances = formset.save(commit = False)
            for instance in instances:
                instance.created_by = request.user
                instance.save()
                formset.save_m2m()
            messages.success(request, 'Projects updated')
            return redirect('project_list')
        messages.error(request, 'Error updating projects')
        return redirect('project_list')

projects/templates/projects/includes/add_project_modal.html
<!-- Modal -->
<div class="modal fade" id="addProjectModal" tabindex="-1" role="dialog" aria-labelledby="addProjectModalTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <form action="{% url 'projects:create' %}" method="POST">
                <div class="modal-header">
                    <h5 class="modal-title" id="addProjectModalTitle">Create Project</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    {% csrf_token %}
                    {% for f in form %}
                        <div class="form-group">
                            {{ f.label }}
                            {{ f }}
                            {% if f.errors %}
                                {{ f.errors }}
                            {% endif %}
                        </div>
                    {% endfor %}
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-primary">Create</button>
                </div>
            </form>
        </div>
    </div>
</div>

projects/templates/projects/includes/delete_project_modal.html
<!-- Modal -->
<div class="modal fade" id="deleteProjectModal{{ p.id }}" tabindex="-1" role="dialog" aria-labelledby="deleteProjectModal{{ p.id }}Title" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <form action="{% url 'projects:delete' pk=p.id %}" method="POST">
                <div class="modal-header">
                    <h5 class="modal-title" id="deleteProjectModal{{ p.id }}Title">Modal title</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    {% csrf_token %}
                    <input type="hidden" name="id" value="{{ p.id }}">
                    <h2>Are you sure you want to delete project {{ p.name }}</h2>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">No</button>
                    <button type="submit" class="btn btn-danger">Yes</button>
                </div>
            </form>
        </div>
    </div>
</div>

projects/templates/projects/includes/update_project_modal.html
<!-- Modal -->
<div class="modal fade" id="updateProjectModal{{ index }}" tabindex="-1" role="dialog" aria-labelledby="updateProjectModal{{ index }}" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="updateProjectModal{{ index }}">Edit Project</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                {% csrf_token %}
                {% for f in form %}
                    <div class="form-group">
                        {{ f.label }}
                        {{ f }}
                        {% if f.errors %}
                            {{ f.errors }}
                        {% endif %}
                    </div>
                {% endfor %}
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <button type="submit" class="btn btn-primary">Update</button>
            </div>
        </div>
    </div>
</div>