project_tasks/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from projects.views import ProjectListView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('projects/', include('projects.urls')),
    path('tasks/', include('tasks.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    re_path('^$', ProjectListView.as_view(), name = 'project_list'),
]

tasks/urls.py
from django.urls import path, re_path
from tasks import views

app_name = 'tasks'

urlpatterns = [
    path('', views.ListTask.as_view(), name = 'list'),
    path('create/', views.CreateTask.as_view(), name = 'create'),
    path('delete/<int:pk>/', views.DeleteTask.as_view(), name = 'delete'),
]

tasks/models.py
from django.db import models
from django.conf import settings
from django.contrib.auth.models import Group

from projects.models import Project


class Task(models.Model):
    name = models.CharField(max_length = 300)
    note = models.TextField(blank = True)
    start = models.DateField(verbose_name = 'Start Date')
    end = models.DateField(verbose_name = 'End Date')
    project = models.ForeignKey(Project, on_delete = models.CASCADE, related_name = 'tasks')
    assigned_users = models.ManyToManyField(
        settings.AUTH_USER_MODEL,
        related_name = 'assigned_tasks',
        blank = True,
    )
    assigned_groups = models.ManyToManyField(
        Group,
        related_name = 'assigned_groups',
        blank = True,
    )
    created_by = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete = models.SET_NULL,
        null = True,
        blank = True,
        related_name = 'created_tasks',
        editable = False,
    )
    updated_by = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete = models.SET_NULL,
        null = True,
        blank = True,
        related_name = 'updated_tasks',
        editable = False,
    )
    updated = models.DateTimeField(auto_now = True)
    created = models.DateTimeField(auto_now_add = True)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ('-created', 'name')

tasks/forms.py
from django import forms
from django.contrib.auth.models import User

from .models import Task
from projects.models import Project

class TaskForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super(TaskForm, self).__init__(*args, **kwargs)
        for f in self.fields:
            self.fields[f].widget.attrs['class'] = 'form-control'
            self.fields[f].widget.attrs['placeholder'] = f
        self.fields['assigned_users'].widget.attrs['class'] += ' select2-multiple'
        self.fields['assigned_groups'].widget.attrs['class'] += ' select2-multiple'
        self.fields['start'].widget.attrs['class'] += ' date-selector'
        self.fields['end'].widget.attrs['class'] += ' date-selector'
        self.fields['start'].widget.attrs['placeholder'] = 'YYYY-MM-DD'
        self.fields['end'].widget.attrs['placeholder'] = 'YYYY-MM-DD'

    class Meta:
        model = Task
        fields = ('name', 'note', 'start', 'end', 'assigned_users', 'assigned_groups')


TaskFormset = forms.inlineformset_factory(
    Project,
    Task,
    TaskForm,
    # fields = ('')
)

tasks/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic import ListView, CreateView, DeleteView, UpdateView
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.urls import reverse_lazy
from django.contrib import messages

from .models import Task
from .forms import TaskForm, TaskFormset
from projects.models import Project


class UpdateTask(UpdateView):
    model = Task

    def post(self, request, *args, **kwargs):
        formset = TaskFormset(request.POST)
        if formset.is_valid():
            for form in formset:
                obj = form.save(commit = False)
                obj.updated_by = request.user
                obj.save()
                form.save_m2m()
            messages.success(request, 'Tasks updated')
        else:
            messages.error(request, 'Error updating tasks')
        return redirect('projects:details', pk = obj.project.id)

class DeleteTask(DeleteView):
    model = Task
    success_url = reverse_lazy('projects')

    def get_object(self, queryset = None):
        id = self.kwargs.get('pk')
        obj = get_object_or_404(Task, id = id)
        return obj

    def delete(self, request, *args, **kwargs):
        obj = self.get_object()
        project_id = obj.project.id
        obj.delete()
        return redirect('projects:details', pk = project_id)


class CreateTask(CreateView):
    model = Task
    form_class = TaskForm

    def form_valid(self, form):
        obj = form.save(commit = False)
        obj.created_by = self.request.user
        obj.updated_by = self.request.user
        obj.project = get_object_or_404(Project, id = self.request.POST.get('project_id'))
        obj.save()
        form.save_m2m()
        return redirect('projects:details', pk = obj.project.id)


class ListTask(LoginRequiredMixin, ListView):
    template_name = 'tasks/list.html'
    context_object_name = 'tasks'

    def get_queryset(self):
        return self.request.user.assigned_tasks.all()

tasks/templates/tasks/includes/add_task_modal.html
<!-- Modal -->
<div class="modal fade" id="addTaskModal" tabindex="-1" role="dialog" aria-labelledby="addTaskModalTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <form action="{% url 'tasks:create' %}" method="POST">
                <div class="modal-header">
                    <h5 class="modal-title" id="addTaskModalTitle">Create Task</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    {% csrf_token %}
                    {% for f in task_form %}
                        <div class="form-group">
                            {{ f.label }}
                            {{ f }}
                            {% if f.errors %}
                                {{ f.errors }}
                            {% endif %}
                        </div>
                    {% endfor %}
                    <input type="hidden" name="project_id" value="{{ project.id }}">
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-primary">Create</button>
                </div>
            </form>
        </div>
    </div>
</div>

tasks/templates/tasks/includes/delete_task_modal.html
<!-- Modal -->
<div class="modal fade" id="deleteTaskModal{{ task.id }}" tabindex="-1" role="dialog" aria-labelledby="deleteTaskModal{{ task.id }}Title" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <form action="{% url 'tasks:delete' pk=task.id %}" method="POST">
                <div class="modal-header">
                    <h5 class="modal-title" id="deleteTaskModal{{ task.id }}Title">Modal title</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    {% csrf_token %}
                    <input type="hidden" name="id" value="{{ task.id }}">
                    <h2>Are you sure you want to delete task {{ task.name }}</h2>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">No</button>
                    <button type="submit" class="btn btn-danger">Yes</button>
                </div>
            </form>
        </div>
    </div>
</div>